all: programa

programa: Amarillo.java Cyan.java Enemigo.java ILevantar.java Juego.java Magenta.java Muralla.java Pieza.java Pikinim.java Pildora.java Zona.java
	javac Amarillo.java Cyan.java Enemigo.java ILevantar.java Juego.java Magenta.java Muralla.java Pieza.java Pikinim.java Pildora.java Zona.java

run:
	java Juego

clean:
	rm -f programa *.class